:lipstick: Add a subscribe button to empty feed
Tubefeeder/Tubefeeder pull request #121
Opened 2023-03-24 13:01 UTC by Schmiddiii

# Licensing 

- [x] I confirm that this is either my code or was released under the terms of a GPLv3-or-later compatible license. Also I agree to release it here under the terms of the GPLv3-or-later.

# Description

This adds a "subscribe"-button to an empty feed page.

![tubefeeder_subscribe_button](https://user-images.githubusercontent.com/48252573/227527986-59afeae6-953e-4849-b519-ca3c338ee2a5.png)

Ping @TheEvilSkeleton if anything can be improved in this regard.

# Linked Issue

Related to #95.

2023-03-24 14:00 UTC, TheEvilSkeleton requested changes
My suggestions aren't final, but I think it's a good start. I'll test once the suggestions are added

2023-03-24 14:00 UTC, TheEvilSkeleton commented on data/resources/ui/feed_page.ui
> +                    <property name="label" translatable="yes">Subscribe to a chanel</property>
I don't think we should be adding a `+` icon. Texts should be fine.

```suggestion
                    <property name="label" translatable="yes">Subscribe to a Channel</property>
```

2023-03-24 14:00 UTC, TheEvilSkeleton commented on data/resources/ui/feed_page.ui
> +                  <class name="pill"/>
Suggesting that button (making it blue) would help the user.

```suggestion
                  <class name="pill"/>
                  <class name="suggested-action"/>
```

2023-03-24 14:39 UTC, TheEvilSkeleton commented
That's normal design for GNOME apps that have an empty startup nowadays; Loupe, Bottles, etc. do that

2023-03-24 18:10 UTC, TheEvilSkeleton requested changes

2023-03-24 18:10 UTC, TheEvilSkeleton commented on data/resources/ui/feed_page.ui
>              <property name="description" translatable="yes">Are you subscribed to channels?</property>
We should remove this, as "No Videos Found" implies to subscribe to a channel
```suggestion
```

2023-03-25 10:01 UTC, Schmiddiii commented
Should we maybe do a similar thing in the filters and subscriptions pages?

2023-03-25 21:12 UTC, TheEvilSkeleton commented
Absolutely! I didn't think of that, but yes, that would be great

2023-03-26 21:30 UTC, TheEvilSkeleton requested changes

2023-03-26 21:30 UTC, TheEvilSkeleton commented on data/resources/ui/filter_page.ui
> +                <property name="label" translatable="yes">Add a Filter</property>
```suggestion
                <property name="label" translatable="yes">Add Filter</property>
```

2023-03-27 13:59 UTC, TheEvilSkeleton commented
> To be honest, I think the suggestive highlighting of the button is too much.

About that, if you don't like how it looks, then you can always remove the style. You maintain and develop it after all

2023-03-27 14:57 UTC, merged